### PR TITLE
Added blinking cursor

### PR DESCRIPTION
**Pull request by NikhilC2209**
Added a blinking background in place of a static cursor.

### CODE REVIEW

**Comment by amanRecreates** [comment]
Hi @NikhilC2209 , thanks for your valuable contribution. Changes seems fine to me. Not sure what is changed in package-lock.json. Can you please brief.

**Comment by amanRecreates** [comment]
@NikhilC2209  Also, I am curious to know how you found this repo 😉

**Comment by NikhilC2209** [comment]
even i am curious what changed in package.json because i made no changes to it directly but it seems to work same as before.

**Comment by NikhilC2209** [comment]
Also I wanted to start with Open Source so I was randomly looking for repos with "good first issue" to begin with.

**Comment by NikhilC2209** [comment]
I've resolved conflicts based on your recent commits.

**Review by amanRecreates — APPROVED** [review]

**Comment by amanRecreates** [comment]
Thanks for your efforts :)

**Pull request merged**
